import type { ExtractedDict } from "./docx-extract";
import templateHtml from "../../template.html?raw";

export interface LLMConfig {
  baseUrl: string;
  apiKey: string;
  model: string;
}

function getSystemPrompt(language: "zh" | "en"): string {
  const languageRules =
    language === "en"
      ? `- The report MUST be written entirely in English. Translate any remaining Chinese labels, headings, and UI text into professional English.`
      : `- Keep the report language consistent with the source content unless the source clearly indicates another language.`;

  return `You are a senior financial research report editor and HTML front-end engineer.
Your job is to generate a polished, standalone HTML report from a source JSON object.

Hard requirements:
- Use the provided @template as the visual and structural reference.
- Use the original JSON keys and values as the source of truth.
- Return ONLY one complete HTML document, no markdown fences, no explanations.
${languageRules}
- Do not fabricate unavailable facts, figures, dates, ratings, or prices.
- The HTML must be browser-runnable as a standalone file.
- Cover page rule (CRITICAL):
  - The cover page must be creatively generated by you (title, subtitle, visual hierarchy, and summary wording).
  - Do NOT build the cover page by mechanically mapping JSON fields one by one.
  - You may infer a professional report title/theme from the data, but keep it concise and editorial.
  - Cover page may be abstracted/editorial, but must not invent concrete facts that conflict with data.
- Data-fill rule (CRITICAL):
  - EXCEPT for the cover page, all sections must be filled from source data.
  - Do not leave body sections as generic placeholders or empty prose.
  - Every key section should render concrete values, tables, bullet points, or extracted statements from JSON.
  - Do not output "N/A" blocks when data exists in JSON under any relevant key.
- IMPORTANT: A global variable \`window.reportData\` is ALREADY defined for you BEFORE any of your scripts run. It contains the FULL source JSON object (with original image data, not placeholders).
  - DO NOT redeclare it. Never write \`const reportData = ...\` or \`let reportData = ...\` or \`var reportData = ...\` at top level.
  - Read it as \`const data = window.reportData || {};\` inside your script.
  - DO NOT add another \`<script id="report-data">\` block — it is already injected.
- The source JSON shape is: \`Record<string, string | Record<string, string>>\`. Keys look like \`p1\`, \`p2\`, \`tc1\`, \`tc2\`, \`img1\`, etc.
  - Top-level VALUES may be either a string OR a nested object of strings. Never assume it is an array; do NOT call \`.forEach\`, \`.map\`, \`.length\` on a value without checking its type first.
  - Iterate with \`Object.entries(data)\` and for each value check \`typeof v === "string"\` vs object.

CRITICAL — Placeholder handling:
- The @curated_report_json below has been compacted for token efficiency:
  - Image objects are replaced with "[img]" placeholders.
  - base64 strings are replaced with "[base64]" placeholders.
  - Image URLs are replaced with "[img-url]" placeholders.
- When you need to render images, use \`window.reportData\` to get the ORIGINAL data:
  - For keys that were "[img]" in the curated JSON, the original \`window.reportData[key]\` may be an object like \`{type:"image", dataUrl:"data:image/...", filename:"...", mimeType:"..."}\`.
    Render it as \`<img src="\${data[key].dataUrl}" />\`.
  - For keys whose leaf values were "[base64]", read the original value from \`window.reportData[key]\`.
- ALWAYS prefer reading from \`window.reportData\` over the curated JSON for any value that looks like a placeholder.

Image sizing requirements:
- ALL images (charts, graphs, figures) MUST be displayed at FULL WIDTH of their container.
- Use style="width:100%;height:auto;" on every <img> tag.
- Never use fixed pixel widths or leave images at their default small size.
- Wrap images in a full-width container: <div style="width:100%"><img ... style="width:100%;height:auto" /></div>
- Charts and graphs from the source document are key visual content — make them prominent and large.

Table & print requirements (CRITICAL):
- This report MUST be printable. NEVER use overflow:auto, overflow-y:auto, overflow-x:auto, or max-height on any table or container.
- NEVER wrap tables in scrollable containers. Tables must be fully visible without scrolling.
- If a table is too wide, make it responsive by: reducing font-size, using shorter headers, or breaking into multiple smaller tables — but NEVER add horizontal scroll.
- If a table is too tall, let it flow naturally across pages — do NOT clip it with max-height or overflow-y.
- All <table> elements should use: \`border-collapse:collapse; width:100%; font-size:10px or smaller;\` to fit within A4 width.
- Add this CSS rule for print: \`@media print { table { page-break-inside:auto; } tr { page-break-inside:avoid; page-break-after:auto; } }\`
- NEVER use \`max-h-*\` tailwind class or \`max-height\` CSS on table containers.

Implementation requirements:
- Prefer safe helper functions for missing keys, for example flattening keys, fallback text, and filtering empty values.
- If charts are not feasible, render elegant summary cards, tables, timelines, and key-value sections instead.
- Avoid external dependencies except lightweight CDN usage already present in the template style.
- Wrap all rendering code in \`try { ... } catch (e) { console.error(e); }\` so one bad field never blanks the whole page.
 - Keep the page visually refined and readable even when some fields are missing.`;
}

export async function generateHtmlReport(
  promptDict: ExtractedDict,
  cfg: LLMConfig,
  originalDict: ExtractedDict,
  signal?: AbortSignal,
): Promise<string> {
  return generateHtmlReportWithPrompt(getSystemPrompt("zh"), promptDict, cfg, originalDict, signal);
}

export async function generateHtmlReportEn(
  promptDict: ExtractedDict,
  cfg: LLMConfig,
  originalDict: ExtractedDict,
  signal?: AbortSignal,
): Promise<string> {
  return generateHtmlReportWithPrompt(getSystemPrompt("en"), promptDict, cfg, originalDict, signal);
}

export function replaceReportData(html: string, newDict: ExtractedDict): string {
  const serialized = safeJsonForScript(newDict);
  const dataScript = `<script id="report-data" type="application/json">${serialized}</script>`;

  // Replace existing report-data script block
  if (/<script[^>]+id=["']report-data["']/i.test(html)) {
    return html.replace(
      /<script[^>]*id=["']report-data["'][^>]*>[\s\S]*?<\/script>/i,
      dataScript,
    );
  }

  // Fallback: shouldn't happen for well-formed reports, but inject into <head>
  if (/<head[^>]*>/i.test(html)) {
    return html.replace(/<head([^>]*)>/i, `<head$1>\n${dataScript}`);
  }

  return `${dataScript}\n${html}`;
}

async function generateHtmlReportWithPrompt(
  systemPrompt: string,
  promptDict: ExtractedDict,
  cfg: LLMConfig,
  originalDict: ExtractedDict,
  signal?: AbortSignal,
): Promise<string> {
  const url = cfg.baseUrl.replace(/\/+$/, "") + "/chat/completions";
  const body = {
    model: cfg.model,
    messages: [
      { role: "system", content: systemPrompt },
      {
        role: "user",
        content:
          [
            "Please generate a polished standalone HTML report.",
            "",
            "@template",
            templateHtml,
            "",
            "@curated_report_json",
            JSON.stringify(promptDict, null, 2),
            "",
            "Important: the curated JSON above is intentionally compacted for token efficiency. When rendering, use window.reportData to access the full original values (images, base64, etc.).",
          ].join("\n"),
      },
    ],
    temperature: 0.3,
  };

  const resp = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${cfg.apiKey}`,
    },
    body: JSON.stringify(body),
    signal,
  });
  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`LLM ${resp.status}: ${text.slice(0, 300)}`);
  }

  const data = await resp.json();
  const content: string = data?.choices?.[0]?.message?.content ?? "";
  const html = parseHtmlLoose(content);
  if (!html) {
    throw new Error("LLM 返回的不是有效 HTML");
  }

  return injectReportData(html, originalDict);
}

function parseHtmlLoose(content: string): string {
  const trimmed = content.trim();
  if (trimmed.startsWith("<!DOCTYPE html") || trimmed.startsWith("<html")) {
    return trimmed;
  }

  const fenced = trimmed.match(/```(?:html)?\s*([\s\S]*?)```/i);
  if (fenced?.[1]) {
    return fenced[1].trim();
  }

  const htmlMatch = trimmed.match(/<!DOCTYPE html[\s\S]*<\/html>/i) ?? trimmed.match(/<html[\s\S]*<\/html>/i);
  return htmlMatch?.[0]?.trim() ?? "";
}

function injectReportData(html: string, dict: ExtractedDict): string {
  const serialized = safeJsonForScript(dict);
  const dataScript = `<script id="report-data" type="application/json">${serialized}</script>`;
  // IIFE — no top-level `const reportData` to avoid clashing with LLM-generated
  // scripts that also declare `const reportData`.
  const bootstrapScript = `<script>(function(){try{var el=document.getElementById("report-data");window.reportData=el?JSON.parse(el.textContent||"{}"):{};}catch(e){console.error("reportData parse failed",e);window.reportData={};}})();</script>`;

  let next = html;

  if (/<script[^>]+id=["']report-data["']/i.test(next)) {
    next = next.replace(
      /<script[^>]*id=["']report-data["'][^>]*>[\s\S]*?<\/script>/i,
      dataScript,
    );
  } else if (/<head[^>]*>/i.test(next)) {
    // Inject as early as possible so any later inline script sees window.reportData.
    next = next.replace(/<head([^>]*)>/i, `<head$1>\n${dataScript}\n${bootstrapScript}`);
  } else if (/<body[^>]*>/i.test(next)) {
    next = next.replace(/<body([^>]*)>/i, `<body$1>\n${dataScript}\n${bootstrapScript}`);
  } else {
    next = `${dataScript}\n${bootstrapScript}\n${next}`;
  }

  // Always also ensure bootstrap runs once after the data script when injected into <head>
  // (already inlined above). Nothing else to do.
  return next;
}


function safeJsonForScript(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}
